### ISSUE TITLE
Mona: Es ist möglich mehrfach den selben baum aufzunehmen

### ISSUE THREAD

**Issue by b-lack** [b-lack/qgis-fim-plugin#35]
![image](https://github.com/b-lack/lfb-regeneration_wildlife_impact_monitoring/assets/11278402/52fd7d5a-f936-487d-bdec-22908c297138)

**Comment by b-lack** [comment]
Sollte meiner Meinung nach möglich sein. Es kommst sicher selten vor, dass gleiche Bäume mit gleichem BHD und gleicher Distanz vorhanden sind...ist aber theoretisch möglich.

**Comment by b-lack** [comment]
Für ganz später

**Comment by twiebke** [comment]
Am selben Punkt kann kein neuer Baum stehen. Das sollte in der Aufnahme abgefangen werden. Ist auch wichtig für die kartographische Darstellung des Baumplotts #21

**Comment by b-lack** [comment]
![image](https://github.com/b-lack/qgis-fim-plugin/assets/11278402/edf5628b-c23d-499f-b9df-f15a29a64588)

**Comment by twiebke** [comment]
Super :) 
Und Dein Beispiel führt gleich zum nächsten Problem. Bei Eingaben von Messhöhen über 22 muss auch eine Fehlermeldung kommen, dass das unrealistisch ist.

**Comment by b-lack** [comment]
![image](https://github.com/b-lack/qgis-fim-plugin/assets/11278402/549e05f3-8fd6-44ca-b13f-9d3ef41b0879)
Eine vorgegebene Range von Zahlenwerten ist kein Problem.
