### ISSUE TITLE
Linus: DD-Bestockung

### ISSUE THREAD

**Issue by b-lack** [b-lack/qgis-fim-plugin#49]
Das Drop-Down-Menü für die Schichtauswahl im Reiter "Bestockung" reicht über das Pluginfenster hinaus, gut wäre eine Kopplung damit, also dass sich die Größe des Menüs dynamisch an die Fenstergröße anpasst, wenn das zu kompliziert ist, wäre zumindest eine Begrenzung auf die default Breite des Fensters schön, dafür müssten Zeilenumbrüche in den einzelnen Auswahlmöglichkeiten eingefügt werden

**Comment by b-lack** [comment]
@twiebke Das Dropdown "Schicht" ist wirklich recht breit. Können wir die Antwortmöglichkeiten kürzen?
(Zwischenstand und Unterstand)

**Comment by twiebke** [comment]
Klar. Ich weiß zwar nicht richtig was gemeint ist aber wir können die kurzd aus der Codeliste nehmen. 
OS für Oberstand
US für Unterstand
MH für Mittelholz = Zwischenstand
wenn ich es richtig im Kopf habe.
