### ISSUE TITLE
Für das FIM  Plugin benötigen wir noch einen beschreibenden Text

### ISSUE THREAD

**Issue by b-lack** [b-lack/qgis-fim-plugin#55]
Aktuell: 

The FIM plugin is a QGIS plugin for the Forest Inventory and Monitoring. FIM supports the recording of forest data based on different inventory methods.

Bei Bedarf überarbeiten.

**Comment by twiebke** [comment]
Das Plugin „Forest Inventory Monitoring“ (FIM) dient der Aufnahme in Brandenburg als Waldinventur nach § 30 LWaldG durchgeführten Waldinventur „Verjüngungszustands- und Wildeinflussmonitoring“ (VWM). 

Es ist geplant es so weiterzuentwickeln, dass es 
1. für Inventuraufnahmen durch Interessierte (Waldbesitzer, Jäger) und
2. für unabhängige, eigenständige Inventuren genutzt werden kann.

Die Dokumentation zum Verfahren VWM findet sich unter https://gitlab.opencode.de/lfe/vwm-verfahren.

Die technische Dokumentation zu FIM findet sich unter: URL

Rückmeldungen an den Entwickler: EMAILADRESSE

Rückmeldungen an den Verfahrensverantwortlichen zur VWM: [landeswaldinventur@lfb.brandenburg.de](mailto:landeswaldinventur@lfb.brandenburg.de) 

---------------------------------------------------------------------------------------------------------------------

The plug-in "Forest Inventory Monitoring" (FIM) is used for the forest inventory "Regeneration Status and Game Influence Monitoring" (VWM) carried out in Brandenburg as a forest inventory according to § 30 LWaldG. 


It is planned to develop it further in such a way that it can be used for 

1. for inventories by interested parties (forest owners, hunters) and

2. for independent, autonomous inventories.


The documentation on the VWM procedure can be found at https://gitlab.opencode.de/lfe/vwm-verfahren.


The technical documentation on FIM can be found at: URL


Feedback to the developer: EMAILADRESSE


Feedback to the person responsible for the VWM procedure: landeswaldinventur@lfb.brandenburg.de
