### ISSUE TITLE
QGIS stürzt bei jeder Nutzereingabe im FIM-Plugin ab

### ISSUE THREAD

**Issue by llissel** [b-lack/qgis-fim-plugin#56]
Seit ca. 2 Wochen (16. Oktober) stürzt beim Testen des FIM-Plugins jedes Mal QGIS ab, sobald ich eine Nutzereingabe vornehme. Sprich sowohl der Klick auf "Einmessung starten", als auch der Versuch einer Eingabe im Feld "Truppkürzel" crashed das Programm. Wenn gewünscht, hänge ich auch gerne noch einen Fehlerreport von QGIS an.

**Comment by b-lack** [comment]
@llissel danke für das Feedback. Nach Tests konnte ich den Fehler nicht reproduzieren.

Es wäre daher gut, wenn du doch die Datei "g_los" die du verwendest, schicken könntest und/oder die Fehlermeldung von QGIS.

**Comment by llissel** [comment]
Hier die Fehlermeldung:

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00001094 (most recent call first):
  File "C:\Users/efcaPAD#4/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\fim\fim.py", line 236 in run
    result = self.dlg.exec_()
```


**Stack Trace**

```

QString::indexOf :
QgsGpsDetector::advance :
QObject::qt_static_metacall :
QgsGpsConnection::stateChanged :
QgsNmeaConnection::parseData :
QObject::qt_static_metacall :
QSerialPort::handle :
KiUserApcDispatch :
NtUserMsgWaitForMultipleObjectsEx :
RealMsgWaitForMultipleObjectsEx :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.32.0-Lima
QGIS code revision: 311a8cb8a6
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by b-lack** [comment]
@llissel scheint ein Performance Problem zu sein. D.h. bis zur nächsten Version muss nicht getestet werden.

**Comment by b-lack** [comment]
@twiebke Zur Info: Die Performance Probleme treten mit steigender Komplexität häufiger auf und führen teilweise zum Absturz von Qgis. Ausschließlich auf Windows. MacOs und Linux haben keine Probleme.

 Ich schalte jetzt nach und nach Funktionen aus um einen vertretbaren Kompromiss aus Funktionen und Performance zu finden.

**Comment by b-lack** [comment]
Nach einigen Tests vermute ich, dass Performanceprobleme (nur unter Windows) auf Statusänderungen zur Laufzeit zurückzuführen sind. Hauptsächlich: Validierung der Eingaben, dynamische Erstellung des Formulars, Speichern von Daten (Zwischenspeichern) ...

Es betrifft also hauptsächlich die Usability und Scalability der Anwendung.

Info @twiebke: Ich baue das Formular nun komplett neu und statisch auf. Leider fallen hierdurch schöne, aber eben nicht "App-Breaking" Funktionen weg. Wenn es hierzu Gesprächsbedarf oder Vorschläge gibt, gerne melden.

**Comment by twiebke** [comment]
Wie ist der Stand?
Ich kann in den nächsten Tagen einmal testen.

**Comment by b-lack** [comment]
@twiebke Ist alles neu und performant. Leider gibt es einen neuen Bug "Nur unter Windows und nur von GPS und nur innerhalb des Plugins" stürzt Qgis ab. Das bedeutet, dass die Integration von GNAVS in FIM funktioniert, dort aber der GPSDetector zum Absturz führt.

wenn du also die Koordinaten manuell eingibst, kannst du alles testen.

**Comment by b-lack** [comment]
Ich habe nun eine potentielle Lösung gefunden. Die Umsetzung wird aber 1-2 Tage dauern.

Ich melde mich, wenn Testen möglich ist.

**Comment by b-lack** [comment]
FIM ist jetzt nicht mehr als Dialog sondern unten in qgis angedockt. Grund ist einfach, dass unter windows qgisGpsDetector nicht im Dialog funktioniert...weiß der Geier warum.

![image](https://github.com/b-lack/qgis-fim-plugin/assets/11278402/45e597fb-cea9-462d-b1e5-7a5dd5bdb1c0)

Wem das zu klein ist, der kann das angedockte Fenster lösen, dann funktioniert es auch:

![image](https://github.com/b-lack/qgis-fim-plugin/assets/11278402/cf6341a7-aca1-4bd2-ab1d-ba67299155fb)

d.h. es kann bitte getestet werden, das werde ich jetzt auch tun.

**Comment by b-lack** [comment]
Kann natürlich auch, je nach Auflösung verschoben werden: 
![image](https://github.com/b-lack/qgis-fim-plugin/assets/11278402/a0976024-76bf-4c29-89c3-f11e273f7809)

**Comment by b-lack** [comment]
@RicRat was meinst du mit "geht mit 12 Sekunden zu schnell"? Ich habe bei verschiedenen Witterungsbedingungen auch unterschiedlich lang gebraucht um 100 Messungen zu machen. Ich nutze die 100 eingehenden Signale vom GNSS-Sensor.

**Comment by b-lack** [comment]
@RicRat ich habe mit den Punkten von Linus getestet, bei mir traten keine Fehler auf. Kannst du mir auch nochmal ein gezipptes Projekt per Mail senden, bei dem der Fehler Auftritt?

**Comment by twiebke** [comment]
> @RicRat was meinst du mit "geht mit 12 Sekunden zu schnell"? Ich habe bei verschiedenen Witterungsbedingungen auch unterschiedlich lang gebraucht um 100 Messungen zu machen. Ich nutze die 100 eingehenden Signale vom GNSS-Sensor.

Die Zeit ist ja abhängig von der Konfiguration der GNSS-Geräte. Bei älteren oder schlecht konfigurierten Geräten kann das schon einmal 100 Sekunden (1Hz) dauern. Es sollte heutzutage selten länger dauern. 
Die Software sollte so gestrickt sein, dass man mit anderen Aufnahmen fortführen kann während die Messung stattfindet.

**Comment by b-lack** [comment]
@twiebke FIM kann weiter bedient werden...wenn es der Rechner hergibt. Das ist aber unabhängig von GNAVS/FIM.

**Comment by RicRat** [comment]
> @RicRat was meinst du mit "geht mit 12 Sekunden zu schnell"? Ich habe bei verschiedenen Witterungsbedingungen auch unterschiedlich lang gebraucht um 100 Messungen zu machen. Ich nutze die 100 eingehenden Signale vom GNSS-Sensor.



Mit einem GNSS-Empfänger, der mit 1 Hz arbeitet, sollte die Messung der 100 Punkte eigentlich 100 Sekunden oder länger dauern. Ich habe dazu auch ein neues Issue erstellt.

Gibt es eine Möglichkeit, ein Log ausgeben zu lassen, um genau zu sehen, mit welchen Messungen das Tool arbeitet?

**Comment by b-lack** [comment]
> Gibt es eine Möglichkeit, ein Log ausgeben zu lassen, um genau zu sehen, mit welchen Messungen das Tool arbeitet?

@RicRat Wenn du im GNAVS Plugin eine Punktaufnahme beendest und "ADD TO MAP" drückst, siehst du alle eingehenden Koordinaten + Timestamp

**Comment by b-lack** [comment]
@RicRat @twiebke Ich möchte das Thema GNSS in das entsprechende Plugin umziehen: https://github.com/b-lack/qgis-gnavs-plugin/issues/27 und dort weiter diskutieren...

**Comment by b-lack** [comment]
@llissel @RicRat Ich konnte den Absturz jetzt zum ersten mal reproduzieren, wird in der kommenden v1.0.15 gefixed. Danke für Euer Feedback.

**Comment by b-lack** [comment]
@twiebke Qgis stürzt ab, wenn vwm4qgis20230427_prfg.qgz geöffnet wird. Wenn die Geopackages einzeln geladen werden, stürzt qgis nicht ab.

Ich nehme also an, dass ein Hintergrund-Service den Absturz verursacht. Wenn der "Fehler" behoben werden soll, müssen wir beide uns zusammensetzen, da du das Projekt besser kennst.

Alternativ werden die Daten in der kommenden Aufnahme eh anders ausgeliefert. Eine Fehlersuche ist somit vielleicht gar nicht nötig.

**Comment by twiebke** [comment]
Es werden ja nur die Rettungspunkte und -wege aus dem Layer angezeigt und es läuft ein wms zu osm. Ich könnte mir vorstellen, dass der wms abruf stört. 
Wir wollen ja mit fim die Daten über eine api abrufen. Den Aufnehmenden muss es aber möglich sein weitere layer hinzuzuladen. Ein WMS ist in Brandenburg eh quatsch. Das in dem genannten Projekt platzierte Formular könnte auch eine Ursache sein und ist ja mit fim auch nicht nötig.

**Comment by b-lack** [comment]
Problem wurde behoben.
