### ISSUE TITLE
Zusätzliches Feld Baumart - NR

### ISSUE THREAD

**Issue by b-lack** [b-lack/qgis-fim-plugin#64]
In der Auswahlliste des Baumart  (im Verjüngungstransekt) wäre evtl. noch eine Nr. vor der Baumart hilfreich, da manche seltene/nicht so relevante Baumarten lokal häufig auftreten und dann ist es einfacher bei wiederholten heraussuchen nach einer Nr . zuschauen. Oder ist es möglich einen weiteren Button zu definieren der pro Punkt von der Aufnehmenden Person selbst definiert werden kann? (Felix)

**Comment by b-lack** [comment]
Das "Problem" kann ab Version 1.0.15 über den Button "Duplizieren" gelöst werden. Alternativ kann in der nächsten Version optimiert werden.

**Comment by RicRat** [comment]
Ist es möglich das der "Duplizieren" Button im Verjünungstransekt den Baum auch automatisch hinzufügt?
