### ISSUE TITLE
Einmessung mit dem FIM - Plugin und dem GNVAS - Plugin

### ISSUE THREAD

**Issue by RicRat** [b-lack/qgis-fim-plugin#66]
Bei der Einmessung sind mir folgende Dinge aufgefallen:

**FIM - Plugin:**
- Mit einem 1 Hz Empfänger dauert die Messung ca. 30s (sollte Theoretisch min. 100s dauern)
- Mit einer Externe Antenne (20 Hz), dauert die Messung 40s.
- Das "Precision"-Feld bleibt wären der Messung grau

**GNVAS Plugin:**

- Mit einem 1 Hz Empfänger dauert die Messung ca. 50s.
- Mit einer Externe Antenne (20 Hz), dauert die Messung 55s.
- Das "Precision"-Feld funktioniert Problemlos

**Comment by b-lack** [comment]
Moved to: https://github.com/b-lack/qgis-gnavs-plugin/issues/27
