### ISSUE TITLE
Baumplot Darstellung bei Wiederholungs und Kontrollaufnahmen

### ISSUE THREAD

**Issue by paulamms** [b-lack/qgis-fim-plugin#83]
Die Baumplot Darstellung funktioniert gerade nicht. Sie wäre aber wichtig für Wiederholungs und Kontrollaufnahmen. 
Ist aber nicht brennend wichtig.

**Comment by b-lack** [comment]
du meinst die KArtendarstellung?

![image](https://github.com/user-attachments/assets/10e562e4-0269-4c1c-9027-621a3b612fae)

**Comment by paulamms** [comment]
Die Baumdaten sind vorhanden und werden auch schon mit übergeben (siehe losnr 2024_01 und 2024_06). 

Für Kontrollaufnahmen würden wir eine Kopie der zu kontrollierenden Punkte mit eigener g_los_id anlegen. Dann natürlich auch mit Kopie der aufgenommenen Baumplots usw.

**Comment by b-lack** [comment]
fixed in https://github.com/b-lack/qgis-fim-plugin/releases/tag/v1.0.26
