### ISSUE TITLE
Eintragen der LosID in ImpEx

### ISSUE THREAD

**Issue by paulamms** [b-lack/qgis-fim-plugin#85]
Momentan wird vom FIM, bei der Synchro, die LosID nicht mit in die Impex Tabellen übertragen. 

Das muss aber geschehen, damit die Einträge bei Kontroll Aufnahmen miteinander verglichen werden können.

**Comment by b-lack** [comment]
Kannst du genau sagen welches Schema->Tabelle->Spalte: zb. "impex.glos.los_id"

**Comment by b-lack** [comment]
Und bis wann das gemacht sein soll bzw. Priorität im Vergleich der anderen offenen Issues.

**Comment by paulamms** [comment]
Schema: vwm_impex

Tabellen: imp_b_strg, imp_b_strgsonstig, imp_t_baumplot, imp_t_besbodenvegge, imp_t_bestbes, imp_t_bestbess, imp_t_landmarke, imp_t_transekt, imp_t_transektinfo, imp_t_transektipf

Spalte: los_id 

Die los_id steht in der tabelle g_los schon mit drin, soll bei der Synchronisation von FIM zu DB mit in die restlichen Tabellen eingetragen werden. Darf NULL sein, wenn keine los_id in der g_los eingetragen war

**Comment by paulamms** [comment]
Prio: über Unterlosnummern, gleich mit Wiederholungsaufnahmen und Kontrollaufnahmen
