### ISSUE TITLE
Fehler in Plausiprüfung

### ISSUE THREAD

**Issue by paulamms** [b-lack/qgis-fim-plugin#87]
Irgendwas scheint mit der Plausiprüfung nicht ganz zu funktionieren: 

1. Es gibt eine Plausipüfung auf der Bestandesbeschreibung, die gab es mMn früher nicht, diese geht weg wenn man bei "n-schichtig*" einen anderen Wert auswählt. 

2. Ich habe von den Trupps ein paar Punkt IDs bekommen, die sich nicht abschließen ließen (FERTIG bleibt ausgegraut).

In diesen Punkten scheint die Plausiprüfung auf dem Baumplot1 buggy zu sein, der Reiter ist rot obwohl der Azimut eingetragen ist und wird auch nicht grün, wenn man den Eintrag verändert. 

Das Phänomen tritt nur bei manchen Punkten auf, und überträgt sich. Wenn ich die Punkte neu reinlade (synch) und als erstes einen Punkt anklicke, wo der Baumplot buggy ist (zb 1415, 1088) dann ist das gleiche Problem auf allen Punkten. 

Wenn ich aber als ersten Punkt, einen öffne, der nicht buggy ist, sind auch alle anderen in Ordnung. Ich kann die "buggy Punkte" (zb 1415, 1088) aber trotzdem nicht abschließen, "FERTIG" bleibt weiter ausgegraut. Wenn ich den Azimut bearbeite, erscheint auch die Plausiprüfung wieder als rot. 

Ich habe noch kein richtiges Muster feststellen können. 

Ich teste noch ein bisschen und versuche rauszufinden woran es liegt. Vielleicht hast du aber schon eine Idee was es sein kann. 

![Screenshot_20241002_135813](https://github.com/user-attachments/assets/9b941dab-afcc-4971-873e-aeebe6b041a2)
![Screenshot_20241002_145209](https://github.com/user-attachments/assets/e7a29ffe-2414-4da1-8d30-e7719e44d822)

**Comment by b-lack** [comment]
STATUS:

(zb 1415, 1088) / Baumplot schlägt fehl, weil schal/Fege NULL sind, was sie nicht sein dürfen. Da FIM die Werte auf false/true setzt und eigentlich nie auf NULL muss ich erstmal fragen:

Setzt oder verändert Ihr die Werte "Fege" o. "Schäle" oder schreibt Ihr die Baumdaten ohne Fege und Schäle (dann sind die default Null)?  

Ich habe jetzt in FIM umgestellt, dass NULL angezeigt wird und nicht False:
![image](https://github.com/user-attachments/assets/ffc95c74-1fdc-4ebf-8ffa-75485f48e534)

(Wir können auch FIM umstellen, dass NULL erlaubt ist bzw wie false behandelt wird. Aber darüber müssen wir sprechen)

**Comment by paulamms** [comment]
Die Baumdaten werden mit Schäle und Fege nach ImpEx geschrieben, aber ich habe gerade gesehen, dass auf dem Produktivschema in der Baumplot Tabelle auch NULL-Werte eingetragen sind. Daher kommt das wahrscheinlich. Ich stelle das mal  entsprechend um.
